[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/swagger/index.html"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Note: PostgreSQL and Redis services must be added manually in Railway dashboard
# Then set these environment variables:
# DATABASE_DSN=${{Postgres.DATABASE_URL}}
# REDIS_URL=${{Redis.REDIS_URL}}

