services:
  - type: web
    name: socio-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /swagger/index.html
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: socio-postgres
          property: connectionString
      - key: DATABASE_DSN
        fromDatabase:
          name: socio-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: socio-redis
          type: redis
          property: connectionString
      - key: PORT
        value: 3015

  - type: redis
    name: socio-redis
    plan: free
    ipAllowList: []

databases:
  - name: socio-postgres
    databaseName: socio
    user: socio
